"""
GIFT-128 cipher constants, taken from:
Banik et al., "GIFT: A Small Present -- Towards Reaching the Limit of
Lightweight Encryption", CHES 2017 (https://eprint.iacr.org/2017/622.pdf),
cross-checked against the reference C / Rust implementations.
"""

# GS (SubCells) S-box: GS = 1a4c6f392db7508e (hex string, GS(0)=1, GS(1)=a, ...)
SBOX = [int(c, 16) for c in "1a4c6f392db7508e"]

INV_SBOX = [0] * 16
for _i, _v in enumerate(SBOX):
    INV_SBOX[_v] = _i
assert all(SBOX[INV_SBOX[i]] == i for i in range(16)), "sbox/invsbox mismatch"

# PermBits: P128 -- identical to BAKSHEESH's permutation (same table is shared
# between BAKSHEESH and GIFT-128 per the BAKSHEESH paper's own note).
# bit i of input state -> bit P128[i] of output state
P128 = [
    0, 33, 66, 99, 96, 1, 34, 67, 64, 97, 2, 35, 32, 65, 98, 3,
    4, 37, 70, 103, 100, 5, 38, 71, 68, 101, 6, 39, 36, 69, 102, 7,
    8, 41, 74, 107, 104, 9, 42, 75, 72, 105, 10, 43, 40, 73, 106, 11,
    12, 45, 78, 111, 108, 13, 46, 79, 76, 109, 14, 47, 44, 77, 110, 15,
    16, 49, 82, 115, 112, 17, 50, 83, 80, 113, 18, 51, 48, 81, 114, 19,
    20, 53, 86, 119, 116, 21, 54, 87, 84, 117, 22, 55, 52, 85, 118, 23,
    24, 57, 90, 123, 120, 25, 58, 91, 88, 121, 26, 59, 56, 89, 122, 27,
    28, 61, 94, 127, 124, 29, 62, 95, 92, 125, 30, 63, 60, 93, 126, 31,
]
assert len(P128) == 128 and sorted(P128) == list(range(128))

INV_P128 = [0] * 128
for i, p in enumerate(P128):
    INV_P128[p] = i

# AddRoundConstant: a fixed "1" bit is always XORed into bit 127 (the MSB),
# and the 6-bit round constant c5 c4 c3 c2 c1 c0 is XORed bit-by-bit into
# nibble-MSB positions 3, 7, 11, 15, 19, 23 (c0 -> bit 3, c5 -> bit 23).
CONST_TAPS = [3, 7, 11, 15, 19, 23]
CONST_FIXED_BIT = 127

# 6-bit round-constant sequence for all 40 rounds, generated by the standard
# GIFT/SKINNY-style affine LFSR (s5 s4 s3 s2 s1 s0 -> s0 = 1, s_{i-1} for
# i>0, with s5 <- s5 XOR s4 XOR 1 fed back each step). Given here as the
# well-known precomputed table (matches the reference C/Rust implementations).
ROUND_CONSTANTS_6BIT = [
    0x01, 0x03, 0x07, 0x0F, 0x1F, 0x3E, 0x3D, 0x3B, 0x37, 0x2F,
    0x1E, 0x3C, 0x39, 0x33, 0x27, 0x0E, 0x1D, 0x3A, 0x35, 0x2B,
    0x16, 0x2C, 0x18, 0x30, 0x21, 0x02, 0x05, 0x0B, 0x17, 0x2E,
    0x1C, 0x38, 0x31, 0x23, 0x06, 0x0D, 0x1B, 0x36, 0x2D, 0x1A,
]
assert len(ROUND_CONSTANTS_6BIT) == 40

NUM_ROUNDS = 40

# Official/known-answer test vectors: (key_hex, plaintext_hex, ciphertext_hex).
# Vector 1 is the canonical all-zero GIFT-128 test vector from the CHES 2017
# paper; vectors 2-3 are additional known-answer vectors used by independent
# reference implementations (e.g. the RustCrypto gift-cipher crate) to
# cross-validate GIFT-128 encryption.
TEST_VECTORS = [
    ("00000000000000000000000000000000",
     "00000000000000000000000000000000",
     "cd0bd738388ad3f668b15a36ceb6ff92"),
    ("fedcba9876543210fedcba9876543210",
     "fedcba9876543210fedcba9876543210",
     "8422241a6dbf5a9346af468409ee0152"),
    ("d0f5c59a7700d3e799028fa9f90ad837",
     "e39c141fa57dba43f08a85b6a91f86c1",
     "13ede67cbdcc3dbf400a62d6977265ea"),
]
